package task

import (
	"sync" // SYNC PACKAGE: Provides mutual exclusion (Mutex) for thread-safe access
	"time"
)

// Status represents the lifecycle state of a task in the distributed scheduler.
// Defined as a string type alias for clarity and type safety.
type Status string

// Task status constants define the possible states a task can be in.
// These states form a state machine with transitions:
// Pending → Running → Completed (success path)
// Pending → Running → Failed → Retrying → Running → ... (retry path)
const (
	StatusPending   Status = "pending"   // Task has been created but not yet picked up by a worker
	StatusRunning   Status = "running"   // Task is currently being executed by a worker
	StatusCompleted Status = "completed" // Task has finished successfully
	StatusFailed    Status = "failed"    // Task execution failed
	StatusRetrying  Status = "retrying"  // Task failed and is queued for retry
)

// Task represents a unit of work to be executed by a worker in the distributed scheduler.
// It contains all metadata necessary for scheduling, tracking, and executing the task.
//
// CONCURRENCY SAFETY:
// This struct is accessed by multiple goroutines (workers, scheduler, monitoring).
// To prevent race conditions, the 'status' field MUST NOT be accessed directly.
// Instead, use SetStatus() and GetStatus() methods which protect access with a mutex.
type Task struct {
	// ID is a unique identifier for this task across the entire distributed system.
	// Used for idempotency, tracking, and preventing duplicate execution.
	// NOTE: ID is immutable after creation, so direct access is safe (no mutex needed).
	ID string

	// Name describes the type or purpose of the task for logging and identification.
	// Helps operators understand what work is being performed.
	// NOTE: Name is immutable after creation, so direct access is safe (no mutex needed).
	Name string

	// Payload contains the task-specific data needed for execution.
	// Stored as bytes to support any serialization format (JSON, Protobuf, etc.).
	// Workers deserialize this based on the task type.
	// NOTE: Payload is immutable after creation, so direct access is safe (no mutex needed).
	Payload []byte

	// RetryCount tracks how many times the task has already been retried.
	// It starts at 0 for new tasks and is incremented on each failed execution.
	RetryCount int

	// MaxRetries controls the maximum number of retry attempts.
	// New tasks are initialized with MaxRetries = 3.
	MaxRetries int

	// status represents the current lifecycle state of the task.
	// ⚠️ PRIVATE FIELD: Must not be accessed directly. Use GetStatus()/SetStatus() instead.
	// Enables the scheduler to make routing and retry decisions.
	//
	// WHY PRIVATE? Direct access by multiple goroutines creates race conditions:
	// - Goroutine A reads t.status (reads "pending")
	// - Goroutine B writes t.status (writes "running")
	// - Goroutine A's read is now stale (it still thinks status is "pending")
	// This can cause incorrect routing decisions and duplicate processing.
	status Status

	// mu is a mutex (mutual exclusion lock) that protects the mutable fields.
	// Only one goroutine can hold the lock at a time.
	// Before reading or writing mutable fields, a goroutine must acquire this lock.
	//
	// MUTEX EXPLANATION:
	// - Lock():   Acquire exclusive access. Blocks if another goroutine holds it.
	// - Unlock(): Release exclusive access, allowing other goroutines to proceed.
	// - Pattern:  Always use defer mu.Unlock() immediately after mu.Lock() to prevent deadlocks.
	mu sync.Mutex

	// CreatedAt is the timestamp when the task was initially submitted to the system.
	// Used for monitoring SLA compliance, calculating task age, and debugging delays.
	// NOTE: CreatedAt is immutable after creation, so direct access is safe (no mutex needed).
	CreatedAt time.Time
}

// NewTask creates a new Task with sensible defaults and the current timestamp.
// This constructor ensures all tasks are initialized consistently.
// The status is initialized to StatusPending (no work has started yet).
//
// PARAMETERS:
//   - id: unique identifier for this task (typically generated by scheduler)
//   - name: human-readable name describing task type (e.g., "process_payment", "generate_report")
//   - payload: binary data containing task parameters (JSON, Protobuf, etc.)
//
// THREAD SAFETY: Newly created tasks are safe to share across goroutines.
// The mutex is pre-initialized (zero value is unlocked) and ready to protect status updates.
func NewTask(id, name string, payload []byte) *Task {
	return &Task{
		ID:         id,
		Name:       name,
		Payload:    payload,
		RetryCount: 0,
		MaxRetries: 3,
		status:     StatusPending, // Initialize in pending state (not yet running)
		CreatedAt:  time.Now(),
		// mu is zero-initialized to an unlocked mutex (ready for use)
	}
}

// GetStatus returns the current status of the task in a thread-safe manner.
// This method acquires a lock before reading the status to ensure memory visibility
// and prevent reading stale/torn values.
//
// HOW THIS PREVENTS RACE CONDITIONS:
// Without the lock:
//   - Goroutine A reads t.status = "pending" ✓
//   - Goroutine B writes t.status = "running" (acquires lock, writes, releases)
//   - But Goroutine A may not see the new value (memory visibility issue)
//     Result: Goroutine A uses stale "pending" status → WRONG DECISION
//
// With the lock:
//   - Goroutine A calls GetStatus() → acquires lock → reads "pending" → releases lock
//   - Goroutine B calls SetStatus("running") → acquires lock → writes "running" → releases lock
//   - Goroutine A calls GetStatus() again → acquires lock → reads "running" → releases lock
//     Result: Goroutine A always sees consistent, up-to-date status → CORRECT
//
// IMPORTANT: Lock must be acquired BEFORE reading, released AFTER reading.
// The defer statement guarantees unlock happens even if this function panics.
func (t *Task) GetStatus() Status {
	// DEFER STATEMENT: Queues the Unlock() call to execute when this function exits.
	// This ensures the lock is ALWAYS released, even if:
	// - The function returns early
	// - The function panics
	// - Multiple return statements exist
	// Without defer, we'd need to manually unlock before every return, risking deadlocks.
	defer t.mu.Unlock()

	// ACQUIRE LOCK: Block until exclusive access is granted.
	// If another goroutine holds the lock, this call blocks (waits) until it's released.
	// Go's scheduler will run other goroutines while we wait, preventing CPU waste.
	t.mu.Lock()

	// READ STATUS: Return the current status value.
	// Now that we hold the lock, we know:
	// 1. No other goroutine can write to status while we're reading
	// 2. Any writes before we acquired the lock are visible to us (memory visibility)
	// 3. This read is "atomic" in terms of semantics (logically indivisible)
	return t.status
}

// SetStatus updates the task status in a thread-safe manner.
// This method is called by workers to transition tasks through their lifecycle:
// Pending → Running (when worker starts execution)
// Running → Completed (when worker finishes successfully)
// Running → Failed (when worker encounters an error)
//
// PARAMETERS:
//   - newStatus: the new status value (StatusPending, StatusRunning, StatusCompleted, StatusFailed, StatusRetrying)
//
// THREAD SAFETY:
// Like GetStatus(), this acquires the lock before writing to prevent:
// 1. Lost updates: Two goroutines writing simultaneously (second write overwrites first)
// 2. Torn reads: Another goroutine reading status while we're mid-write
// 3. Memory visibility: Changes not visible to other goroutines without synchronization
//
// EXAMPLE RACE CONDITION (without mutex):
// Timeline:
//
//	T1: Worker1.SetStatus(Running) - writes bit 0
//	T2: Worker2.SetStatus(Completed) - writes bit 1 (interrupts Worker1's write!)
//	T3: Worker1.SetStatus(Running) - finishes writing bit 0
//
// Result: status = partial update from both workers = CORRUPTION
// With mutex: Only one write happens at a time, preventing corruption.
func (t *Task) SetStatus(newStatus Status) {
	// DEFER + LOCK: Same pattern as GetStatus().
	// Critical: defer is evaluated AFTER the lock is acquired.
	// Order of execution:
	// 1. t.mu.Lock() runs immediately (acquires lock)
	// 2. defer t.mu.Unlock() is registered to run at function exit
	// 3. t.status = newStatus runs with lock held
	// 4. Function returns, defer runs (releases lock)
	defer t.mu.Unlock()
	t.mu.Lock()

	// WRITE STATUS: Update the status with lock held.
	// Now that we hold the lock, we know:
	// 1. No other goroutine can read or write to status during this operation
	// 2. Our write will be visible to all other goroutines that acquire the lock after we release it
	// 3. This operation is atomic from the perspective of other goroutines
	t.status = newStatus
}

// CanRetry returns true when the task has failed but has not exceeded MaxRetries.
// This helper centralizes retry logic so workers can decide whether to re-enqueue.
func (t *Task) CanRetry() bool {
	return t.GetStatus() == StatusFailed && t.RetryCount < t.MaxRetries
}

// IncrementRetry increments RetryCount and returns the current retry attempt.
// This must be called when a task is about to be retried.
func (t *Task) IncrementRetry() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.RetryCount < t.MaxRetries {
		t.RetryCount++
	}
	return t.RetryCount
}

// IsTerminalState returns true if the task has reached a final state
// and will not change further without external intervention.
// Useful for determining if a task can be removed from the queue or reported as complete.
//
// Terminal states indicate the task has finished (successfully or not):
// - StatusCompleted: Task succeeded
// - StatusFailed: Task failed (may be retried later)
//
// Non-terminal states indicate ongoing work:
// - StatusPending: Not yet started
// - StatusRunning: Currently executing
// - StatusRetrying: Queued for retry attempt
//
// THREAD SAFETY: Uses GetStatus() which acquires the lock, so this is safe to call
// concurrently from multiple goroutines.
func (t *Task) IsTerminalState() bool {
	// GET STATUS: Call the thread-safe getter.
	// This acquires the lock, reads status, releases the lock.
	currentStatus := t.GetStatus()

	// CHECK TERMINAL STATE: Compare against terminal status values.
	// Only Completed and Failed are terminal.
	// If a task is failed, it might be retried (Retrying state), so it's not truly terminal.
	// But for practical purposes, a failed task won't progress without external action.
	return currentStatus == StatusCompleted || currentStatus == StatusFailed
}
